export const abscences = [
  {
    user_id: 1,
    leaves: [
      {
        type: "Holiday",
        duration_from: new Date(),
        duration_to: new Date(),
        duration: 4,
        status: "cancelled",
      },
      {
        type: "Special leave",
        duration_from: new Date(),
        duration_to: new Date(),
        duration: 1,
        status: "approved",
      },
      {
        type: "Holiday",
        duration_from: new Date(),
        duration_to: new Date(),
        duration: 4,
        status: "cancelled",
      },
      {
        type: "Holiday",
        duration_from: new Date(),
        duration_to: new Date(),
        duration: 4,
        status: "approved",
      },
    ],
    requested_holidays: 0,
    requested_others: 0,
    approved_holidays: 0,
    approved_others: 0,
  },
  {
    user_id: 2,
    leaves: [],
    requested_holidays: 0,
    requested_others: 0,
    approved_holidays: 0,
    approved_others: 0,
  },
  {
    user_id: 3,
    leaves: [],
    requested_holidays: 0,
    requested_others: 0,
    approved_holidays: 0,
    approved_others: 0,
  },
  {
    user_id: 4,
    leaves: [],
    requested_holidays: 0,
    requested_others: 0,
    approved_holidays: 0,
    approved_others: 0,
  },
  {
    user_id: 5,
    leaves: [],
    requested_holidays: 0,
    requested_others: 0,
    approved_holidays: 0,
    approved_others: 0,
  },
  {
    user_id: 6,
    leaves: [],
    requested_holidays: 0,
    requested_others: 0,
    approved_holidays: 0,
    approved_others: 0,
  },
  {
    user_id: 7,
    leaves: [],
    requested_holidays: 0,
    requested_others: 0,
    approved_holidays: 0,
    approved_others: 0,
  },
  {
    user_id: 8,
    leaves: [],
    requested_holidays: 0,
    requested_others: 0,
    approved_holidays: 0,
    approved_others: 0,
  },
  {
    user_id: 9,
    leaves: [],
    requested_holidays: 0,
    requested_others: 0,
    approved_holidays: 0,
    approved_others: 0,
  },
  {
    user_id: 10,
    leaves: [],
    requested_holidays: 0,
    requested_others: 0,
    approved_holidays: 0,
    approved_others: 0,
  },
];
